#!/usr/bin/with-contenv bash

run_hangup () {
    echo -e "\n======================== 启动挂机程序 ========================\n"
    rm -rf /root/.pm2/logs/* >/dev/null 2>&1
    if [[ $ENABLE_HANGUP == true ]]; then
        if [ -f $JD_DIR/config/cookie.sh ]; then
            . $JD_DIR/config/cookie.sh
        fi
        . $JD_DIR/config/config.sh
        if [[ $Cookie1 ]]; then
            jtask hangup 2>/dev/null
            echo -e "挂机程序启动成功...\n"
        else
            echo -e "$JD_DIR/config/config.sh 中还未填入有效的Cookie，可能是首次部署容器，因此不启动挂机程序...\n"
        fi
    elif [[ ${ENABLE_HANGUP} == false ]]; then
        echo -e "已设置为不自动启动挂机程序，跳过...\n"
    fi
}


run_hangup 2>&1 | perl -pe "s|^(.+)|[cont-init.d] $(basename $0): \1|g"